### ISSUE TITLE
Issue tracker for #8, #9, #12

### ISSUE THREAD

**Issue by diamondburned** [diamondburned/gotk4#11]
Since the 3 new issues seem very daunting, this issue will be created just to
keep track of the progress of the other issues.

## Package changes

- [x] Decouple everything away from `girgen`
- [x] `girgen` to only contain `Generator`
	- [x] Common generator sets containing the right pens and side effects to
		write code to; ideally, both `NamespaceGenerator` and `FileGenerator`
		should easily be able to include them.
	- [x] Subpackage `namespacegen` having `NamespaceGenerator`
	- [x] Subpackage `filegen` having `FileGenerator` that extends
		`NamespaceGenerator`
- [x] `generators` to contain all generators for classes, interfaces, enums,
	records, etc.
	- [x] Subpackage `callable` that generates specifically just callables.
- [x] String utilities (mostly concerned with casing) should go into `strcases`.
- [x] Comment utilities should go into `cmt`.
- [x] Templating utilities should go into `gotmpl`.
- [x] Hard-wired types, such as primitives, should go into `types`.
	- [x] Type conversion, resolving and trees should go here as well.

#### Directory Tree

```
gir
├── girgen
│   ├── cmt
│   │   └── cmt.go
│   ├── file
│   │   └── file.go
│   ├── generators
│   │   ├── callable
│   │   │   ├── callable.go
│   │   │   └── c.go
│   │   ├── alias.go
│   │   ├── bitfield.go
│   │   ├── callback.go
│   │   ├── class.go
│   │   ├── enum.go
│   │   ├── function.go
│   │   ├── generators.go
│   │   ├── interface.go
│   │   └── record.go
│   ├── gotmpl
│   │   └── gotmpl.go
│   ├── logger
│   │   └── logger.go
│   ├── strcases
│   │   ├── capitalized.txt
│   │   └── strcases.go
│   ├── types
│   │   ├── typeconv
│   │   │   ├── c->go.go
│   │   │   ├── go->c.go
│   │   │   └── typeconv.go
│   │   ├── filter.go
│   │   ├── generator.go
│   │   ├── resolve.go
│   │   ├── tree.go
│   │   └── types.go
│   ├── file.go
│   ├── generator.go
│   └── namespace.go
├── pkgconfig
│   ├── pkgconfig.go
│   └── pkgconfig_test.go
├── gir.go
├── LICENSE.md
├── repository.go
└── types.go
```

## Issue Trackers

Since this is a huge refactor, there will be a lot code to be (re)written.
Because of that, the order of these issues are organized in this order.

- [x] File generators, https://github.com/diamondburned/gotk4/issues/9
	- This change involves writing a new file generator instance.
- [x] Type Resolver interfaces, https://github.com/diamondburned/gotk4/issues/8
	- This change involves adding new interfaces into the `girgen` package that
		allows exposing the current namespaces as well as a logging API.
- [x] Conservative pointer conversion and handling, #12 
	- This change will allow some edge cases to be user-handled.
	- It removes the complicated `convertRef` routine.
- ~~Array reference types, https://github.com/diamondburned/gotk4/issues/10~~
