### ISSUE TITLE
Progress

### ISSUE THREAD

**Issue by diamondburned** [diamondburned/gotk4#2]
This issue keeps track of what's accomplished in the repository.

- [ ] Types and signatures
  - [x] Arrays
  - [x] Enums
  - [x] Functions
    - [x] Signatures
      - ~~No missing types~~
      - [x] Boxed pointer types with `interface{}`
    - [x] Implementation (see "Type resolver and converter")
  - [x] Callback
  - [x] Structs (records)
    - [x] Type
    - [x] Methods
  - [x] Classes
    - [x] Methods
  - [x] Interfaces
    - [x] Methods (as functions)
    - [x] Virtual methods (as the interface body)
  - [ ] Add all missing types (as PRs to gotk3/glib)
    - [ ] `glib.Parameter`
    - [ ] `glib.ParamSpec`
    - [ ] `glib.Callback`
- [ ] Type resolver and converter
  - [x] Type resolver
    - [x] Array type resolver
  - [ ] Type converter
    - [x] Arrays
      - [x] 1-level deep
      - [ ] Infinite recursion
      - [x] GArray (can preallocate)
      - [x] Null-terminated
    - [ ] Types
      - [ ] Custom GLib types
        - [x] GType
        - [x] GValue
        - [x] GObject
        - [x] GInitiallyUnowned
        - [ ] GCallback
      - [x] Enums and Bitfields
      - [x] Aliases
      - [x] Callbacks and Functions
        - [x] CGo signature headers (`extern`)
        - [x] Base wraps
        - [x] Destroy notifiers
      - [x] Classes and Records
        - [x] Base conversions (`glib.Take` and copying record fields)
        - [x] Wrap function and parent wrap resolver
        - [x] Memory management (ownership)

Current package list:

- atk
- gdk
- gdkpixbuf
- gdkpixdata
- gdkwayland
- gdkx11
- gio
- glib
- gobject
- graphene
- gsk
- gtk
- pango
- pangocairo

**Comment by firelizzard18** [comment]
Is this something you'd like help with?

**Comment by diamondburned** [comment]
> Is this something you'd like help with?

Oh definitely, though the code is kind of all over the place right now, and priority isn't clearly defined enough for collaboration, but the code base is far from being done.

Right now, I'm working on adding proper allocation support into the code and then build it, then see how far that takes me.

As far as missing things go, when you `go generate` the root directory, there will be lots of logs printing what is skipped and why, so I think that's a good place to start. 

P/S: the type conversion routine is incomplete; I commented them out because I wanted to properly reuse the conversion process for the destination type, but that would require some extra tinkering. I'll leave it commented out for now (so the code that needs them are skipped) because they're low priority, but you're more than welcomed to give it a shot.

**Comment by diamondburned** [comment]
As a sidenote, I've went ahead and made a contributing guideline over at [CONTRIBUTING.md](https://github.com/diamondburned/gotk4/blob/4/CONTRIBUTING.md).

**Comment by firelizzard18** [comment]
I was thinking of using Vulcan, which was the primary driver for my interest in GTK4. I've since decided to stick with OpenGL, though I am still interested in helping with this, if I have the time.
